### ISSUE TITLE
Type mismatch, Expected: Nothing, actual: Any

### ISSUE THREAD

**Issue by superhigh** [lihaoyi/Metascala#4]
In Thread.scala, there is a type mismatch: 

    case UnaryOp(src, psrc, dest, pout, func) =>                       
            pout.write(func(psrc.read(reader(frame.locals, src))), writer(frame.locals, dest))
            advancePc()

I use sbt 0.13.9 with scala 2.11.8.
I'm a new of scala, I search for this problem, but didn't find any solution.
Hope you can help me. Thank you.

**Comment by lihaoyi** [comment]
This is fixed in master
